language: python
python:
- '2.7'
- '3.5'
install:
- pip install -r requirements.txt
script: python test_example.py
deploy:
  provider: pypi
  user: goodspeed
  password:
    secure: eLs2qPU9w8lBdH2nzPeaCdaVs8A6z6Z0OAjW674pJ/du7AXHGlIbZwIt47JOOmA9xnKi5HBZ0C+80DkSTAN5vUftQyKTQj0mdGU2gTo2Bh9qbdiJpylm3zlm35GO25FheB7n5eYADJTTibkjqicR11jRtFZcKZbYdemgAgChdy86Re9+6Y4E6puMX+t4OSz93qTwz/R2lP5CJHQGh2vGXnqrcJES+rCD1KDhy2ykzzBoZc5Eq8LH9ouW7Cax6smt8iTVUpkW2STMM0Ivdu7GXeSouGZ74tD9X76rwrqAnWT/1Prhf9DisfU0AJsFStcnYKMlFp75KFFQXUM4regTKyw30CAibxsuh1U1DBYdt3O36qAVpYrynJKMZ9ofzisKDBUl5sSHY1II468koclkIJrsssK6Qm+ogwBgCUIUyH07AsFuFqaLQOMgcVtzfUvSH7W82MQlsqd02J0ji8kav7jkyU+x+L3TnHmu/nhq1RXBDwR7B7r7YDrUy07dNkdQYUhQ9aN+7VVWxcLWNON3AiVyrOxG/kuu/1vqsxtgglOUlBvHEoXPWZNwg+793EFEY0Wqg82PyOZ3/LVCqyM7Kfnh9QAp1hNUo6iv8QZX6G3IlRrlr2LrB4lz9iXnpC+bbmZ11Cpkg+BgFL3jvcnDRX6rqv5RBEQ0azZ+NkIcXYE=
true:
  pythoni: 2.7
  tags: true
  branch: master
